version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python-app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database